#!/bin/bash

# Create a new directory and enter it
mkd() {
    mkdir -p "$@"
    cd "$@" || exit
}

# Make a temporary directory and enter it
tmpd() {
	local dir
	if [ $# -eq 0 ]; then
		dir=$(mktemp -d)
	else
		dir=$(mktemp -d -t "${1}.XXXXXXXXXX")
	fi
	cd "$dir" || exit
}

# Get colors in manual pages
man() {
	env \
		LESS_TERMCAP_mb="$(printf '\e[1;31m')" \
		LESS_TERMCAP_md="$(printf '\e[1;31m')" \
		LESS_TERMCAP_me="$(printf '\e[0m')" \
		LESS_TERMCAP_se="$(printf '\e[0m')" \
		LESS_TERMCAP_so="$(printf '\e[1;44;33m')" \
		LESS_TERMCAP_ue="$(printf '\e[0m')" \
		LESS_TERMCAP_us="$(printf '\e[1;32m')" \
		man "$@"
}

homeMonitorSetup() {
	# This function sets the xrandr display modes for my desk in NYC.
	xrandr --output eDP1 --primary --mode 3840x2160 --rate 60 --below DP2-1 \
		--output DP1 --mode 2560x1440 --rate 60  --rotate normal --pos 0x900  \
		--output DP2-1 --mode 2560x1440 --rate 60  --rotate right --pos 3840x0
}

gitsetoriginnopush() {
	git remote set-url --push origin no_push
}
